Fix `ocm create cluster --ccs --provider=aws`
Provider id can be "aws", never "AWS".  The wrong comparison
caused the CCS code to always send GCP fields,
and never send AWS fields, resulting in error:

$ go run ./cmd/ocm create cluster cben-5 --dry-run --ccs --aws-access-key-id=AKIA3EM67QKY33CSWLMK --aws-secret-access-key=(cat ~/.aws/credentials | grep aws_secret_access_key | cut --delimiter=' ' --fields=3 | tr -d \n) --debuggo run ./cmd/ocm create cluster cben-5 --dry-run --ccs --aws-account-id=765374464689 --aws-access-key-id=AKIA3EM67QKY33CSWLMK --aws-secret-access-key=(cat ~/.aws/credentials | grep aws_secret_access_key | cut --delimiter=' ' --fields=3 | tr -d \n) --debug
...
I1221 20:00:21.217566  369671 dump.go:136] Request body follows
I1221 20:00:21.218108  369671 dump.go:258] {
  "kind": "Cluster",
  "api": {
    "listening": "external"
  },
  "ccs": {
    "kind": "CCS",
    "enabled": true
  },
  "gcp": {
    "auth_uri": "",
    "auth_provider_x509_cert_url": "",
    "client_id": "",
    "client_x509_cert_url": "",
    "client_email": "",
    "private_key": "",
    "private_key_id": "",
    "project_id": "",
    "token_uri": "",
    "type": ""
  },
  "cloud_provider": {
    "kind": "CloudProvider",
    "id": "aws"
  },
  "display_name": "cben-5",
  "flavour": {
    "kind": "Flavour",
    "id": "osd-4"
  },
  "multi_az": false,
  "name": "cben-5",
  "nodes": {
    "compute": 4
  },
  "properties": {},
  "region": {
    "kind": "CloudRegion",
    "id": "us-east-1"
  }
}
...
I1221 20:00:21.494533  369671 dump.go:258] {
  "kind": "Error",
  "id": "400",
  "href": "/api/clusters_mgmt/v1/errors/400",
  "code": "CLUSTERS-MGMT-400",
  "reason": "Client email '' received in the service account credentials, has a wrong format of email address.",
  "operation_id": "1hn99dbuqnb5i651bjm52l0nlc0t85u6"
}
Error: Failed to create cluster: dry run: unable to create cluster: identifier is '400', code is 'CLUSTERS-MGMT-400' and operation identifier is '1hn99dbuqnb5i651bjm52l0nlc0t85u6': Client email '' received in the service account credentials, has a wrong format of email address.
exit status 1

Now sends correct request:

I1221 20:11:51.880928  378395 dump.go:258] {
  "kind": "Cluster",
  "api": {
    "listening": "external"
  },
  "aws": {
    "access_key_id": "AKIA3EM67QKY33CSWLMK",
    "account_id": "765374464689",
    "secret_access_key": "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"
  },
  "ccs": {
    "kind": "CCS",
    "enabled": true
  },
  "cloud_provider": {
    "kind": "CloudProvider",
    "id": "aws"
  },
  "display_name": "cben-5",
  "flavour": {
    "kind": "Flavour",
    "id": "osd-4"
  },
  "multi_az": false,
  "name": "cben-5",
  "nodes": {
    "compute": 4
  },
  "properties": {},
  "region": {
    "kind": "CloudRegion",
    "id": "us-east-1"
  }
}